name: Deploy to WordPress.org
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v*"
  # pull_request:
  #   tags:
  #     - "v*"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable pnpm
        run: corepack enable
      - name: Install dependencies
        run: pnpm i
      - name: Vite build
        run: pnpm build

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: ./
          SLUG: warp-driven-visual-search
